"""Tests for Asgard.Bragi.common.context_classifier (Plan 04 Phase A)."""

from Asgard.Bragi.common.context_classifier import (
    AstSignals,
    CodeContext,
    ast_signals_from_python_source,
    classify,
    classify_python_file,
)


class TestFileLevelClassification:
    def test_production_file(self):
        assert classify("src/service.py") == CodeContext.PRODUCTION

    def test_pytest_file_under_tests_dir(self):
        assert classify("tests/test_service.py") == CodeContext.TEST

    def test_helper_under_tests_dir_without_test_signature_is_still_test_dir(self):
        # Heimdall's file-level cascade requires test dir AND test filename;
        # a non-test-named helper under tests/ is production at file level.
        assert classify("tests/helpers.py") == CodeContext.PRODUCTION

    def test_generated_path_convention(self):
        assert classify("api/v1_pb2.py") == CodeContext.GENERATED

    def test_generated_header_peek(self):
        head = b"# Code generated by protoc-gen-go. DO NOT EDIT.\n"
        assert classify("api/thing.go", head_bytes=head) == CodeContext.GENERATED

    def test_no_generated_header_stays_production(self):
        head = b"# a normal module\nimport os\n"
        assert classify("api/thing.py", head_bytes=head) == CodeContext.PRODUCTION

    def test_structural_entropy_fallback_flags_suspected(self):
        signals = AstSignals(line_count=3000, comment_count=0, distinct_statement_kinds=2)
        assert classify("data/big_table.py", ast_signals=signals) == CodeContext.SUSPECTED_GENERATED

    def test_entropy_fallback_requires_no_comments(self):
        signals = AstSignals(line_count=3000, comment_count=10, distinct_statement_kinds=2)
        assert classify("data/big_table.py", ast_signals=signals) == CodeContext.PRODUCTION

    def test_script_dir(self):
        assert classify("scripts/migrate.py") == CodeContext.SCRIPT

    def test_main_guard_dominant_module_is_script(self):
        signals = AstSignals(has_main_guard=True, function_count=1, class_count=0)
        assert classify("tools/run.py", ast_signals=signals) == CodeContext.SCRIPT

    def test_main_guard_in_a_real_library_is_not_script(self):
        signals = AstSignals(has_main_guard=True, function_count=20, class_count=5)
        assert classify("lib/core.py") == CodeContext.PRODUCTION
        assert classify("lib/core.py", ast_signals=signals) == CodeContext.PRODUCTION


class TestPurity:
    def test_classification_is_deterministic(self):
        results = {classify("tests/test_x.py") for _ in range(5)}
        assert results == {CodeContext.TEST}


class TestPythonSourceConvenience:
    def test_classify_python_file_generated_header(self):
        source = "# Code generated by tool. DO NOT EDIT.\nX = 1\n"
        assert classify_python_file("out/gen.py", source) == CodeContext.GENERATED

    def test_classify_python_file_production(self):
        source = "def f():\n    return 1\n"
        assert classify_python_file("src/f.py", source) == CodeContext.PRODUCTION

    def test_ast_signals_from_source_detects_main_guard(self):
        source = 'def main():\n    pass\n\nif __name__ == "__main__":\n    main()\n'
        signals = ast_signals_from_python_source(source)
        assert signals.has_main_guard is True
        assert signals.function_count == 1
