"""
Heimdall Config Pattern Definitions

Pattern definitions for detecting configuration security issues.
"""

import re
from typing import List, Optional

from Asgard.Heimdall.Security.Infrastructure.models.infra_models import InfraFindingType
from Asgard.Heimdall.Security.models.security_models import SecuritySeverity


class ConfigPattern:
    """Defines a pattern for detecting configuration security issues."""

    def __init__(
        self,
        name: str,
        pattern: str,
        finding_type: InfraFindingType,
        severity: SecuritySeverity,
        title: str,
        description: str,
        cwe_id: str,
        remediation: str,
        config_key: Optional[str] = None,
        recommended_value: Optional[str] = None,
        confidence: float = 0.7,
    ):
        self.name = name
        self.pattern = re.compile(pattern, re.IGNORECASE | re.MULTILINE)
        self.finding_type = finding_type
        self.severity = severity
        self.title = title
        self.description = description
        self.cwe_id = cwe_id
        self.remediation = remediation
        self.config_key = config_key
        self.recommended_value = recommended_value
        self.confidence = confidence


CONFIG_PATTERNS: List[ConfigPattern] = [
    ConfigPattern(
        name="debug_mode_true",
        pattern=r"""DEBUG\s*[=:]\s*(?:True|true|1|yes|on|['"](?:True|true|1|yes|on)['"])""",
        finding_type=InfraFindingType.DEBUG_MODE,
        severity=SecuritySeverity.CRITICAL,
        title="Debug Mode Enabled",
        description="DEBUG mode is enabled. This exposes sensitive information and stack traces in production.",
        cwe_id="CWE-489",
        remediation="Set DEBUG = False in production. Use environment variables to control this setting.",
        config_key="DEBUG",
        recommended_value="False",
        confidence=0.95,
    ),
    ConfigPattern(
        name="flask_debug_true",
        pattern=r"""app\.(?:debug|run\([^)]*debug\s*=\s*True)""",
        finding_type=InfraFindingType.DEBUG_MODE,
        severity=SecuritySeverity.CRITICAL,
        title="Flask Debug Mode Enabled",
        description="Flask debug mode is enabled. This allows arbitrary code execution via the debugger.",
        cwe_id="CWE-489",
        remediation="Never run Flask with debug=True in production. Use a production WSGI server.",
        config_key="debug",
        recommended_value="False",
        confidence=0.95,
    ),
    ConfigPattern(
        name="allowed_hosts_wildcard",
        pattern=r"""ALLOWED_HOSTS\s*[=:]\s*\[?\s*['"]\*['"]\s*\]?""",
        finding_type=InfraFindingType.PERMISSIVE_HOSTS,
        severity=SecuritySeverity.HIGH,
        title="Permissive ALLOWED_HOSTS (*)",
        description="ALLOWED_HOSTS is set to '*' which allows any host. This enables HTTP Host header attacks.",
        cwe_id="CWE-16",
        remediation="Set ALLOWED_HOSTS to a specific list of valid hostnames for your application.",
        config_key="ALLOWED_HOSTS",
        recommended_value='["your-domain.com"]',
        confidence=0.95,
    ),
    ConfigPattern(
        name="cors_allow_all",
        pattern=r"""CORS_ORIGIN_ALLOW_ALL\s*[=:]\s*(?:True|true|1)""",
        finding_type=InfraFindingType.CORS_ALLOW_ALL,
        severity=SecuritySeverity.HIGH,
        title="CORS Allow All Origins",
        description="CORS is configured to allow all origins. This bypasses same-origin policy protections.",
        cwe_id="CWE-942",
        remediation="Set CORS_ORIGIN_ALLOW_ALL = False and specify allowed origins explicitly.",
        config_key="CORS_ORIGIN_ALLOW_ALL",
        recommended_value="False",
        confidence=0.95,
    ),
    ConfigPattern(
        name="cors_credentials_allow_all",
        pattern=r"""CORS_ALLOW_CREDENTIALS\s*[=:]\s*(?:True|true|1)[\s\S]{0,100}CORS_ORIGIN_ALLOW_ALL\s*[=:]\s*(?:True|true|1)""",
        finding_type=InfraFindingType.CORS_ALLOW_ALL,
        severity=SecuritySeverity.CRITICAL,
        title="CORS Allow Credentials with All Origins",
        description="CORS is configured to allow credentials with all origins. This is a critical security vulnerability.",
        cwe_id="CWE-942",
        remediation="Never allow credentials with all origins. Specify allowed origins explicitly.",
        config_key="CORS_ALLOW_CREDENTIALS",
        recommended_value="False (or use specific origins)",
        confidence=0.98,
    ),
    ConfigPattern(
        name="access_control_allow_origin_star",
        pattern=r"""Access-Control-Allow-Origin['"]\s*[=:,]\s*['"]\*['"]""",
        finding_type=InfraFindingType.CORS_ALLOW_ALL,
        severity=SecuritySeverity.HIGH,
        title="CORS Header Allow All Origins",
        description="Access-Control-Allow-Origin header is set to '*'. This disables cross-origin restrictions.",
        cwe_id="CWE-942",
        remediation="Set Access-Control-Allow-Origin to specific allowed origins.",
        config_key="Access-Control-Allow-Origin",
        recommended_value="Specific origin",
        confidence=0.9,
    ),
    ConfigPattern(
        name="secure_cookie_false",
        pattern=r"""(?:SESSION_COOKIE_SECURE|CSRF_COOKIE_SECURE|COOKIE_SECURE)\s*[=:]\s*(?:False|false|0)""",
        finding_type=InfraFindingType.INSECURE_DEFAULT,
        severity=SecuritySeverity.HIGH,
        title="Secure Cookie Disabled",
        description="Secure flag is disabled for cookies. Cookies can be transmitted over unencrypted connections.",
        cwe_id="CWE-614",
        remediation="Set SESSION_COOKIE_SECURE = True in production to ensure cookies are only sent over HTTPS.",
        config_key="SESSION_COOKIE_SECURE",
        recommended_value="True",
        confidence=0.9,
    ),
    ConfigPattern(
        name="httponly_cookie_false",
        pattern=r"""(?:SESSION_COOKIE_HTTPONLY|CSRF_COOKIE_HTTPONLY)\s*[=:]\s*(?:False|false|0)""",
        finding_type=InfraFindingType.INSECURE_DEFAULT,
        severity=SecuritySeverity.MEDIUM,
        title="HttpOnly Cookie Disabled",
        description="HttpOnly flag is disabled for cookies. Cookies can be accessed via JavaScript (XSS risk).",
        cwe_id="CWE-1004",
        remediation="Set SESSION_COOKIE_HTTPONLY = True to prevent JavaScript access to session cookies.",
        config_key="SESSION_COOKIE_HTTPONLY",
        recommended_value="True",
        confidence=0.9,
    ),
    ConfigPattern(
        name="ssl_redirect_disabled",
        pattern=r"""SECURE_SSL_REDIRECT\s*[=:]\s*(?:False|false|0)""",
        finding_type=InfraFindingType.INSECURE_TRANSPORT,
        severity=SecuritySeverity.MEDIUM,
        title="SSL Redirect Disabled",
        description="HTTPS redirect is disabled. Users may access the application over unencrypted HTTP.",
        cwe_id="CWE-319",
        remediation="Set SECURE_SSL_REDIRECT = True to force HTTPS in production.",
        config_key="SECURE_SSL_REDIRECT",
        recommended_value="True",
        confidence=0.85,
    ),
    ConfigPattern(
        name="hsts_disabled",
        pattern=r"""SECURE_HSTS_SECONDS\s*[=:]\s*(?:0|None|null)""",
        finding_type=InfraFindingType.MISSING_SECURITY_HEADER,
        severity=SecuritySeverity.MEDIUM,
        title="HSTS Disabled",
        description="HTTP Strict Transport Security is disabled. Browsers will not enforce HTTPS.",
        cwe_id="CWE-319",
        remediation="Set SECURE_HSTS_SECONDS to at least 31536000 (1 year) in production.",
        config_key="SECURE_HSTS_SECONDS",
        recommended_value="31536000",
        confidence=0.85,
    ),
    ConfigPattern(
        name="verbose_errors",
        pattern=r"""(?:PROPAGATE_EXCEPTIONS|SHOW_ERRORS|DISPLAY_ERRORS)\s*[=:]\s*(?:True|true|1|on)""",
        finding_type=InfraFindingType.VERBOSE_ERROR_MESSAGES,
        severity=SecuritySeverity.HIGH,
        title="Verbose Error Messages Enabled",
        description="Verbose error messages are enabled. This exposes internal implementation details.",
        cwe_id="CWE-209",
        remediation="Disable verbose error messages in production. Log errors internally instead.",
        config_key="PROPAGATE_EXCEPTIONS",
        recommended_value="False",
        confidence=0.85,
    ),
    ConfigPattern(
        name="security_disabled",
        pattern=r"""(?:SECURITY_ENABLED|AUTHENTICATION_REQUIRED|AUTH_REQUIRED)\s*[=:]\s*(?:False|false|0|off)""",
        finding_type=InfraFindingType.DISABLED_SECURITY_FEATURE,
        severity=SecuritySeverity.CRITICAL,
        title="Security Feature Disabled",
        description="A security feature is explicitly disabled in configuration.",
        cwe_id="CWE-16",
        remediation="Enable security features in production. Review why this was disabled.",
        config_key="SECURITY_ENABLED",
        recommended_value="True",
        confidence=0.9,
    ),
    ConfigPattern(
        name="csrf_disabled",
        pattern=r"""(?:CSRF_ENABLED|WTF_CSRF_ENABLED|CSRF_PROTECTION)\s*[=:]\s*(?:False|false|0)""",
        finding_type=InfraFindingType.DISABLED_SECURITY_FEATURE,
        severity=SecuritySeverity.CRITICAL,
        title="CSRF Protection Disabled",
        description="Cross-Site Request Forgery protection is disabled. Application is vulnerable to CSRF attacks.",
        cwe_id="CWE-352",
        remediation="Enable CSRF protection. Set CSRF_ENABLED = True.",
        config_key="CSRF_ENABLED",
        recommended_value="True",
        confidence=0.95,
    ),
    ConfigPattern(
        name="xss_protection_disabled",
        pattern=r"""(?:X_XSS_PROTECTION|XSS_PROTECTION)\s*[=:]\s*(?:False|false|0|off|disabled)""",
        finding_type=InfraFindingType.DISABLED_SECURITY_FEATURE,
        severity=SecuritySeverity.HIGH,
        title="XSS Protection Disabled",
        description="Browser XSS protection header is disabled.",
        cwe_id="CWE-79",
        remediation="Enable XSS protection header: X-XSS-Protection: 1; mode=block",
        config_key="X_XSS_PROTECTION",
        recommended_value="1; mode=block",
        confidence=0.85,
    ),
    ConfigPattern(
        name="content_type_nosniff_disabled",
        pattern=r"""(?:X_CONTENT_TYPE_OPTIONS|CONTENT_TYPE_NOSNIFF)\s*[=:]\s*(?:False|false|0|off|disabled)""",
        finding_type=InfraFindingType.MISSING_SECURITY_HEADER,
        severity=SecuritySeverity.MEDIUM,
        title="Content Type Nosniff Disabled",
        description="X-Content-Type-Options header is disabled. Browser may MIME-sniff responses.",
        cwe_id="CWE-16",
        remediation="Set X-Content-Type-Options: nosniff header.",
        config_key="X_CONTENT_TYPE_OPTIONS",
        recommended_value="nosniff",
        confidence=0.8,
    ),
    ConfigPattern(
        name="frame_options_disabled",
        pattern=r"""(?:X_FRAME_OPTIONS|FRAME_OPTIONS)\s*[=:]\s*(?:False|false|off|disabled|['"]ALLOWALL['"])""",
        finding_type=InfraFindingType.MISSING_SECURITY_HEADER,
        severity=SecuritySeverity.HIGH,
        title="Clickjacking Protection Disabled",
        description="X-Frame-Options header is disabled or set to ALLOWALL. Application is vulnerable to clickjacking.",
        cwe_id="CWE-1021",
        remediation="Set X-Frame-Options to DENY or SAMEORIGIN.",
        config_key="X_FRAME_OPTIONS",
        recommended_value="DENY",
        confidence=0.85,
    ),
]
