"""
Linter configuration templates for GAIA projects.

Contains the canonical linting configurations derived from GAIA coding standards.
These templates are used by the LinterInitializer to generate config files.
"""

from Asgard.Heimdall.Init._templates_python import (
    COVERAGE_PYPROJECT_TOML,
    MYPY_PYPROJECT_TOML,
    PRE_COMMIT_CONFIG,
    PYTEST_PYPROJECT_TOML,
    PYTHON_TEMPLATES,
    PYTHON_TOOL_REQUIREMENTS,
    RUFF_PYPROJECT_TOML,
    RUFF_TOML,
    VSCODE_EXTENSIONS_PYTHON,
    VSCODE_SETTINGS_PYTHON,
)
from Asgard.Heimdall.Init._templates_typescript import (
    ESLINT_CONFIG_JS,
    PRETTIERRC_JSON,
    TSCONFIG_JSON,
    TYPESCRIPT_NPM_REQUIREMENTS,
    TYPESCRIPT_TEMPLATES,
    TYPESCRIPT_TOOL_REQUIREMENTS,
    VSCODE_EXTENSIONS_TYPESCRIPT,
    VSCODE_SETTINGS_TYPESCRIPT,
)

__all__ = [
    "RUFF_PYPROJECT_TOML",
    "MYPY_PYPROJECT_TOML",
    "PYTEST_PYPROJECT_TOML",
    "COVERAGE_PYPROJECT_TOML",
    "PRE_COMMIT_CONFIG",
    "RUFF_TOML",
    "ESLINT_CONFIG_JS",
    "TSCONFIG_JSON",
    "PRETTIERRC_JSON",
    "PYTHON_TEMPLATES",
    "TYPESCRIPT_TEMPLATES",
    "VSCODE_SETTINGS_PYTHON",
    "VSCODE_SETTINGS_TYPESCRIPT",
    "VSCODE_EXTENSIONS_PYTHON",
    "VSCODE_EXTENSIONS_TYPESCRIPT",
    "PYTHON_TOOL_REQUIREMENTS",
    "TYPESCRIPT_TOOL_REQUIREMENTS",
    "TYPESCRIPT_NPM_REQUIREMENTS",
]
