"""
Mock Server Generator Helpers.

Code generation helper functions for MockServerGeneratorService.
"""

import json

from Asgard.Forseti.MockServer.models.mock_models import (
    MockEndpoint,
    MockServerConfig,
    MockServerDefinition,
)


def endpoint_to_function_name(endpoint: MockEndpoint) -> str:
    """Convert an endpoint to a valid function name."""
    if endpoint.operation_id:
        name = str(endpoint.operation_id).replace("-", "_").replace(".", "_")
        return name
    path_parts = endpoint.path.strip("/").replace("{", "").replace("}", "")
    path_parts = path_parts.replace("/", "_").replace("-", "_")
    return f"{endpoint.method.value.lower()}_{path_parts}"


def generate_flask_route(endpoint: MockEndpoint, config: MockServerConfig) -> str:
    """Generate a single Flask route."""
    flask_path = endpoint.path.replace("{", "<").replace("}", ">")
    func_name = endpoint_to_function_name(endpoint)
    default_status = endpoint.default_response or "200"
    response_key = f"{endpoint.method.value}_{endpoint.path}_{default_status}"
    delay_code = ""
    if config.response_delay_ms > 0:
        delay_code = f"\n        time.sleep({config.response_delay_ms / 1000})"
    return f'''    @app.route("{flask_path}", methods=["{endpoint.method.value}"])
    def {func_name}(**kwargs):
        """{endpoint.summary or endpoint.description or f"Mock {endpoint.method.value} {endpoint.path}"}"""{delay_code}
        response_data = MOCK_RESPONSES.get("{response_key}", {{}})
        return jsonify(response_data), {default_status}'''


def generate_flask_routes(server_def: MockServerDefinition, config: MockServerConfig) -> str:
    """Generate Flask routes file."""
    routes = []
    for endpoint in server_def.endpoints:
        route_code = generate_flask_route(endpoint, config)
        routes.append(route_code)
    routes_str = "\n\n".join(routes)
    return f'''"""
API Routes for {server_def.title}
"""

import time
from flask import Flask, jsonify, request
from mock_data import MOCK_RESPONSES


def register_routes(app: Flask):
    """Register all mock routes with the Flask app."""

{routes_str}
'''


def generate_flask_main(server_def: MockServerDefinition, config: MockServerConfig) -> str:
    """Generate Flask main server file."""
    cors_import = "from flask_cors import CORS" if config.enable_cors else ""
    cors_init = "CORS(app)" if config.enable_cors else ""
    return f'''"""
{server_def.title} - Mock Server
Generated by Forseti MockServer

{server_def.description or ""}
"""

from flask import Flask, jsonify
{cors_import}
from routes import register_routes

app = Flask(__name__)
{cors_init}

# Register all routes
register_routes(app)


@app.errorhandler(404)
def not_found(e):
    return jsonify({{"error": "Not found"}}), 404


@app.errorhandler(500)
def server_error(e):
    return jsonify({{"error": "Internal server error"}}), 500


if __name__ == "__main__":
    app.run(
        host="{config.host}",
        port={config.port},
        debug=True
    )
'''


def generate_response_data(server_def: MockServerDefinition) -> str:
    """Generate Python mock data file."""
    mock_data = {}
    for endpoint in server_def.endpoints:
        for status_code, response in endpoint.responses.items():
            response_key = f"{endpoint.method.value}_{endpoint.path}_{status_code}"
            mock_data[response_key] = response.body
    data_json = json.dumps(mock_data, indent=4, default=str)
    return f'''"""
Mock response data for {server_def.title}
"""

MOCK_RESPONSES = {data_json}
'''


def generate_fastapi_route(endpoint: MockEndpoint, config: MockServerConfig) -> str:
    """Generate a single FastAPI route."""
    method_lower = endpoint.method.value.lower()
    func_name = endpoint_to_function_name(endpoint)
    default_status = endpoint.default_response or "200"
    response_key = f"{endpoint.method.value}_{endpoint.path}_{default_status}"
    delay_code = ""
    if config.response_delay_ms > 0:
        delay_code = f"\n    time.sleep({config.response_delay_ms / 1000})"
    return f'''@app.{method_lower}("{endpoint.path}")
async def {func_name}():{delay_code}
    """{endpoint.summary or endpoint.description or f"Mock {endpoint.method.value} {endpoint.path}"}"""
    return MOCK_RESPONSES.get("{response_key}", {{}})'''


def generate_express_route(endpoint: MockEndpoint, config: MockServerConfig) -> str:
    """Generate a single Express.js route."""
    express_path = endpoint.path
    for param in endpoint.path_parameters:
        express_path = express_path.replace(f"{{{param.name}}}", f":{param.name}")
    method_lower = endpoint.method.value.lower()
    default_status = endpoint.default_response or "200"
    response_key = f"{endpoint.method.value}_{endpoint.path}_{default_status}"
    delay_code = ""
    if config.response_delay_ms > 0:
        delay_code = f'''
    await new Promise(resolve => setTimeout(resolve, {config.response_delay_ms}));'''
    return f'''// {endpoint.summary or f"{endpoint.method.value} {endpoint.path}"}
app.{method_lower}('{express_path}', {"async " if delay_code else ""}(req, res) => {{{delay_code}
    const response = mockData['{response_key}'] || {{}};
    res.status({default_status}).json(response);
}});'''
