"""
Bragi Context Classifier (Plan 04 Phase A).

Shared context classifier for Quality scanners, the debt analyzer, Ratings,
and Dependencies: one function, used everywhere, so "is this test code" or
"is this generated" is never re-guessed differently by different consumers.

Test-path/filename detection is delegated to
``Asgard.Heimdall.Security.context.test_context`` so Bragi and Heimdall
share ONE source of truth for what counts as a test file. Direct reuse of
that module's ``classify_file_context``/``ContextTag`` is used rather than
re-implementing the regex cascade; Bragi only adds the GENERATED/SCRIPT
layers that Heimdall's security-focused classifier has no need for.

Generated-code detection is a 3-layer funnel (DEEPTHINK_03 Sec.5):
    1. Path convention (`generated/`, `.pb.go`, `_pb2.py`, ...)
    2. 512-byte header peek for "Code generated by" / "@generated" /
       "DO NOT EDIT" style markers.
    3. Structural-entropy fallback: large, comment-free, highly repetitive
       files are flagged SUSPECTED_GENERATED (informational, not certain).

Script detection: module-scope-dominant entry points (`if __name__ ==
"__main__"` with little else, or files under a conventional `scripts/`
directory).
"""

import ast
import re
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Optional, Sequence

from Asgard.Heimdall.Security.context.test_context import (
    ContextTag as _HeimdallContextTag,
    classify_file_context as _heimdall_classify_file_context,
)


class CodeContext(str, Enum):
    """Code context a file (or scope) belongs to."""
    PRODUCTION = "production"
    TEST = "test"
    GENERATED = "generated"
    SUSPECTED_GENERATED = "suspected_generated"
    SCRIPT = "script"


@dataclass(frozen=True)
class AstSignals:
    """
    Cheap structural signals used by the generated/script layers.

    Callers that already have an AST (e.g. Quality scanners) can populate
    this directly instead of Bragi re-parsing the file.
    """
    line_count: int = 0
    comment_count: int = 0
    has_main_guard: bool = False
    top_level_statement_count: int = 0
    function_count: int = 0
    class_count: int = 0
    distinct_statement_kinds: int = 0


# --------------------------------------------------------------------------
# Generated-code detection (layer 1: path conventions)
# --------------------------------------------------------------------------

_GENERATED_PATH_RE = re.compile(
    r"(?:^|/)(?:generated|gen|__generated__|\.generated)(?:/|$)"
    r"|\.pb\.go$|_pb2\.py$|_pb2_grpc\.py$|\.g\.cs$|\.g\.dart$"
    r"|/migrations/\d{4}.*\.py$"
    r"|\.designer\.cs$",
    re.IGNORECASE,
)

# --------------------------------------------------------------------------
# Generated-code detection (layer 2: header peek, first 512 bytes)
# --------------------------------------------------------------------------

_GENERATED_HEADER_RE = re.compile(
    rb"(?:Code generated by|@generated|DO NOT EDIT|AUTO-?GENERATED|"
    rb"This file was automatically generated|GENERATED FILE)",
    re.IGNORECASE,
)

_HEADER_PEEK_BYTES = 512

# --------------------------------------------------------------------------
# Generated-code detection (layer 3: structural-entropy fallback)
# --------------------------------------------------------------------------

_ENTROPY_MIN_LINES = 2000


def _looks_structurally_generated(signals: AstSignals) -> bool:
    """
    Large, comment-free, low-diversity files: flagged SUSPECTED_GENERATED.

    Conservative on purpose (DEEPTHINK_03): false positives here merely
    exclude a file from maintainability metrics with a note, they do not
    silence security scanning.
    """
    if signals.line_count < _ENTROPY_MIN_LINES:
        return False
    if signals.comment_count > 0:
        return False
    # Repetitive AST: few distinct statement kinds relative to volume.
    if signals.distinct_statement_kinds and signals.distinct_statement_kinds <= 3:
        return True
    return False


def _is_generated_path(path: str) -> bool:
    return bool(_GENERATED_PATH_RE.search(path))


def _is_generated_header(head_bytes: bytes) -> bool:
    if not head_bytes:
        return False
    return bool(_GENERATED_HEADER_RE.search(head_bytes[:_HEADER_PEEK_BYTES]))


# --------------------------------------------------------------------------
# Script detection
# --------------------------------------------------------------------------

_SCRIPT_DIR_RE = re.compile(r"(?:^|/)(?:scripts|bin|tools)(?:/|$)", re.IGNORECASE)


def _is_script(path: str, signals: Optional[AstSignals]) -> bool:
    if _SCRIPT_DIR_RE.search(_norm(path)):
        return True
    if signals is not None and signals.has_main_guard:
        # Module-scope-dominant: little besides the main guard and a
        # handful of top-level calls/imports (not a library with an
        # incidental __main__ block).
        if signals.function_count <= 3 and signals.class_count == 0:
            return True
    return False


def _norm(path: str) -> str:
    return str(path).replace("\\", "/")


# --------------------------------------------------------------------------
# Public API
# --------------------------------------------------------------------------

def classify(
    path: "str | Path",
    head_bytes: bytes = b"",
    ast_signals: Optional[AstSignals] = None,
    strict_scan_paths: Sequence[str] = (),
) -> CodeContext:
    """
    Classify a file's context.

    Precedence: TEST (via Heimdall's shared classifier) beats GENERATED
    beats SCRIPT beats PRODUCTION. Test code that happens to be generated
    (e.g. a generated mock) is treated as TEST — its DAMP profile still
    applies and it should not be silently excluded from coverage-adjacent
    metrics the way GENERATED production code is.
    """
    str_path = _norm(str(path))
    heimdall_tag = _heimdall_classify_file_context(str_path, strict_scan_paths=strict_scan_paths)
    if heimdall_tag is not _HeimdallContextTag.PRODUCTION:
        return CodeContext.TEST

    if _is_generated_path(str_path) or _is_generated_header(head_bytes):
        return CodeContext.GENERATED

    if ast_signals is not None and _looks_structurally_generated(ast_signals):
        return CodeContext.SUSPECTED_GENERATED

    if _is_script(str_path, ast_signals):
        return CodeContext.SCRIPT

    return CodeContext.PRODUCTION


def ast_signals_from_python_source(source: str) -> AstSignals:
    """Derive `AstSignals` from Python source text (best-effort; pure)."""
    lines = source.splitlines()
    comment_count = sum(1 for line in lines if line.strip().startswith("#"))
    has_main_guard = bool(re.search(r"if\s+__name__\s*==\s*[\"']__main__[\"']", source))
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return AstSignals(
            line_count=len(lines), comment_count=comment_count,
            has_main_guard=has_main_guard,
        )
    top_level = list(tree.body)
    functions = [n for n in top_level if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))]
    classes = [n for n in top_level if isinstance(n, ast.ClassDef)]
    kinds = {type(n).__name__ for n in ast.walk(tree)}
    return AstSignals(
        line_count=len(lines),
        comment_count=comment_count,
        has_main_guard=has_main_guard,
        top_level_statement_count=len(top_level),
        function_count=len(functions),
        class_count=len(classes),
        distinct_statement_kinds=len(kinds),
    )


def classify_python_file(
    path: "str | Path", source: str, strict_scan_paths: Sequence[str] = ()
) -> CodeContext:
    """Convenience wrapper: classify a Python file from its full source text."""
    head = source.encode("utf-8", errors="ignore")[:_HEADER_PEEK_BYTES]
    signals = ast_signals_from_python_source(source)
    return classify(path, head_bytes=head, ast_signals=signals, strict_scan_paths=strict_scan_paths)
