"""
TypeScript Generator Helpers.

Code generation helper functions for TypeScriptGeneratorService.
"""

from typing import Any

from Asgard.Forseti.CodeGen.models.codegen_models import (
    CodeGenConfig,
    GeneratedFile,
    HttpClientType,
    MethodDefinition,
    TargetLanguage,
    TypeDefinition,
)
from Asgard.Forseti.CodeGen.services._typescript_generator_parse_helpers import (
    generate_ts_type_imports,
    json_type_to_ts,
)
from Asgard.Forseti.CodeGen.services._typescript_generator_request_helpers import (
    generate_method_params,
    generate_ts_request_method,
)


def generate_ts_type(type_def: TypeDefinition, include_documentation: bool) -> list[str]:
    """Generate TypeScript code for a type definition."""
    lines: list[str] = []

    if type_def.description and include_documentation:
        lines.append("/**")
        lines.append(f" * {type_def.description}")
        lines.append(" */")

    if type_def.is_enum:
        lines.append(f"export type {type_def.name} = ")
        enum_values = [
            f'"{v}"' if isinstance(v, str) else str(v)
            for v in type_def.enum_values
        ]
        lines[-1] += " | ".join(enum_values) + ";"
    else:
        lines.append(f"export interface {type_def.name} {{")

        for prop_name, prop_def in type_def.properties.items():
            if prop_def.description and include_documentation:
                lines.append(f"  /** {prop_def.description} */")

            optional = "?" if not prop_def.required else ""
            nullable = " | null" if prop_def.nullable else ""

            lines.append(f"  {prop_name}{optional}: {prop_def.type_name}{nullable};")

        lines.append("}")

    return lines


def generate_types_file(types: dict[str, TypeDefinition], spec_data: dict[str, Any], config: CodeGenConfig) -> GeneratedFile:
    """Generate the types.ts file."""
    lines: list[str] = []

    info = spec_data.get("info", {})
    lines.append("/**")
    lines.append(f" * {info.get('title', 'API')} - Type Definitions")
    lines.append(" * ")
    lines.append(" * Generated by Forseti CodeGen")
    if info.get("version"):
        lines.append(f" * API Version: {info.get('version')}")
    lines.append(" */")
    lines.append("")

    for type_name, type_def in types.items():
        type_code = generate_ts_type(type_def, config.include_documentation)
        lines.extend(type_code)
        lines.append("")

    content = "\n".join(lines)

    return GeneratedFile(
        path="types.ts",
        content=content,
        language=TargetLanguage.TYPESCRIPT,
        file_type="types",
        line_count=len(lines),
    )


def generate_ts_api_method(method: MethodDefinition, config: CodeGenConfig) -> list[str]:
    """Generate a single TypeScript API method."""
    lines: list[str] = []

    if config.include_documentation and method.description:
        lines.append("  /**")
        lines.append(f"   * {method.description}")
        if method.deprecated:
            lines.append("   * @deprecated")
        for param in method.parameters:
            if param.description:
                lines.append(f"   * @param {param.name} - {param.description}")
        lines.append("   */")

    params = generate_method_params(method)
    return_type = method.response_type or "void"

    lines.append(f"  async {method.name}({params}): Promise<{return_type}> {{")

    path_params = [p for p in method.parameters if p.location == "path"]
    query_params = [p for p in method.parameters if p.location == "query"]

    path = method.path
    for param in path_params:
        path = path.replace(f"{{{param.name}}}", f"${{{param.name}}}")

    lines.append(f"    const path = `{path}`;")

    if query_params:
        lines.append("    const query = {")
        for param in query_params:
            lines.append(f"      {param.name},")
        lines.append("    };")

    request_options = []
    if query_params:
        request_options.append("query")
    if method.request_body_type:
        request_options.append("body: data")

    options_str = ", { " + ", ".join(request_options) + " }" if request_options else ""

    lines.append(f"    return this.request<{return_type}>('{method.http_method}', path{options_str});")
    lines.append("  }")

    return lines


def generate_ts_client_file(methods: list[MethodDefinition], types: dict[str, TypeDefinition], spec_data: dict[str, Any], config: CodeGenConfig) -> GeneratedFile:
    """Generate the client.ts file."""
    lines: list[str] = []
    info = spec_data.get("info", {})

    lines.append("/**")
    lines.append(f" * {info.get('title', 'API')} - API Client")
    lines.append(" * ")
    lines.append(" * Generated by Forseti CodeGen")
    lines.append(" */")
    lines.append("")

    type_imports = generate_ts_type_imports(methods, types)
    if type_imports:
        lines.append(f"import {{ {', '.join(sorted(type_imports))} }} from './types';")
        lines.append("")

    lines.append("export interface ApiClientConfig {")
    lines.append("  baseUrl: string;")
    lines.append("  headers?: Record<string, string>;")
    if config.http_client == HttpClientType.FETCH:
        lines.append("  fetchFn?: typeof fetch;")
    lines.append("}")
    lines.append("")

    lines.extend([
        "export class ApiError extends Error {",
        "  constructor(",
        "    message: string,",
        "    public status: number,",
        "    public response?: unknown",
        "  ) {",
        "    super(message);",
        "    this.name = 'ApiError';",
        "  }",
        "}",
        "",
        "export class ApiClient {",
        "  private baseUrl: string;",
        "  private headers: Record<string, string>;",
    ])
    if config.http_client == HttpClientType.FETCH:
        lines.append("  private fetchFn: typeof fetch;")
    lines.append("")

    lines.extend([
        "  constructor(config: ApiClientConfig) {",
        "    this.baseUrl = config.baseUrl.replace(/\\/$/, '');",
        "    this.headers = {",
        "      'Content-Type': 'application/json',",
        "      ...config.headers,",
        "    };",
    ])
    if config.http_client == HttpClientType.FETCH:
        lines.append("    this.fetchFn = config.fetchFn || fetch;")
    lines.extend(["  }", ""])

    lines.extend(generate_ts_request_method(config))
    lines.append("")

    for method in methods:
        lines.extend(generate_ts_api_method(method, config))
        lines.append("")

    lines.extend(["}", "", "export default ApiClient;"])

    content = "\n".join(lines)

    return GeneratedFile(
        path="client.ts",
        content=content,
        language=TargetLanguage.TYPESCRIPT,
        file_type="client",
        line_count=len(lines),
    )
